### ISSUE TITLE
Inline code with `<` characters does not parse correctly (html inside inline code)

### ISSUE THREAD

**Issue by remorses** [ProseMirror/prosemirror-markdown#103]
serializing this markdown document
```
code `<p>`
```

generates the following markdown
```
code
```

**Comment by marijnh** [comment]
The markdown-it library strips out HTML tags, probably because not doing so would open up a lot of usages to cross-site scripting. Since our parser (this is happening in the parser, not the serializer) uses that for tokenizing, they are stripped in our `MarkdownParser` as well. Whether that is a good idea I'm not entirely sure, but I don't see an easy way to tell MarkdownIt to treat HTML tags as plain text.

**Comment by remorses** [comment]
Sorry i must have messed up with my own code and thought the problem was in [prosemirror-markdown](https://github.com/ProseMirror/prosemirror-markdown), but only the testing library has this problem
