### ISSUE TITLE
Punycode is now a hard-dependency?

### ISSUE THREAD

**Issue by WofWca** [ProseMirror/prosemirror-markdown#111]
We have a Vite project and it warns about `punycode`: https://codeberg.org/webxdc/editor/issues/47

Should it be upgraded from a dev dependency to a regular one?

https://github.com/ProseMirror/prosemirror-markdown/blob/c7210d0e55c82bfb0b2f7cba5dffe804575fafb3/package.json#L30-L34

**Comment by WofWca** [comment]
Actually this could be an even more upstream issue https://github.com/markdown-it/markdown-it/issues/230

**Comment by marijnh** [comment]
Yeah, unfortunately, markdown-it seems to be largely unmaintained and somewhat stuck in the past. There's not much I can do about this issue on my side, though.

**Comment by WofWca** [comment]
> There's not much I can do about this issue on my side, though

Wouldn't moving `"punycode"` do `"dependencies"` help? It would make npm automatically install it on each project that depends on `prosemirror-markdown`, so the bundler wouldn't complain that it's missing. Or am I wrong here?

**Comment by marijnh** [comment]
That seems messy, and not really the correct solution (strict bundlers that require all dependencies to be properly declared, rather than just present in the node_modules dir, will still not accept it).

I'm hoping markdown-it gets a new maintainer, or a solid fork, at some point. If not, we'll have to make the move to another parser, which is going to be disruptive.
