### ISSUE TITLE
[Bug] default parser and serializer cannot handle `\t` special character

### ISSUE THREAD

**Issue by Bistard** [ProseMirror/prosemirror-markdown#126]
![image](https://github.com/user-attachments/assets/6967d125-c015-458a-88e0-a7dbec979b4d)
The output of this line of code is: `paragraph1\n\nparagraph2`. `\t` is somehow ignored.

**Comment by marijnh** [comment]
Markdown parsers will treat lines with only whitespace on them as blank lines in most circumstances, thus markdown-it (the parser library we use) is dropping that tab. You'll see the same when you put a space instead of a tab there.

This is intentional behavior—Markdown is too messy to provide any kind of guarantees like round-tripping through the parser and serializer keeping a string intact.
