### ISSUE TITLE
Adding images after spaces wraps image markdown in code block

### ISSUE THREAD

**Issue by buddh4** [ProseMirror/prosemirror-markdown#48]
When adding spaces before an image in the wysiwyg the image markdown will be wrapped in a code block. How could we escape such a case?

![grafik](https://user-images.githubusercontent.com/9800854/95967015-1171d000-0e0c-11eb-8266-cc3c87d985f4.png)

**Comment by marijnh** [comment]
Could you describe more precisely what you are doing? Adding an image after a space to the document in the ProseMirror editor on https://prosemirror.net/examples/markdown/ and then switching to markdown doesn't do anything unexpected.

**Comment by buddh4** [comment]
Sorry, here some infos how to reproduce:

- Go to https://prosemirror.net/examples/markdown/
- Change to WYSIWYM
- Enter a new paragraph
- Add 4 spaces
- Click Insert -> Image
- Add location e.g. https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
- Switch to Markdown and Back to WYSIWYM

**Comment by marijnh** [comment]
Ah, okay, that doesn't appear to be related to images, since the same thing happens with text. It seems Markdown doesn't provide a way to escape spaces, and requires parsers to strip leading spaces. So there's not much this serializer can do to preserve those.

More generally, having spaces at the start of a paragraph like that suggests you're trying to do layout with spaces, which is rarely a good idea anyway (HTML will collapse them, for example).

**Comment by marijnh** [comment]
Markdown, unfortunately, turns out to be somewhat problematic as a serialization format when users aren't directly writing it, since it has a bunch of these corner cases that make some documents unrepresentable.

I don't think I'll be able to address this one at in this module, so I'm closing this issue.
