### ISSUE TITLE
Support for restricted HTML

### ISSUE THREAD

**Issue by segevfiner** [ProseMirror/prosemirror-markdown#85]
Many Markdown renderers such as GitHub, or VS Code, allow a restricted subset of HTML syntax in the Markdown they support. Besides allowing for a few formatting options and tags that are missing from basic Markdown, this also makes markdown-it properly identify stuff like HTML comments, as otherwise they are passed though as text into the editor.

I think they do so by running an HTML sanitizer on rendered HTML of the Markdown, rather than doing something at the parser/tokens level.

For parity with such Markdown files, is there any reasonable way to support such things using prosemirror-markdown? While remaining safe from any XSS of course.

**Comment by marijnh** [comment]
You could probably add opaque HTML nodes to your schema and wire them up in the parser and serializer, doing sanitizing either on parsing or on output (but this is not something that's part of the prosemirror-markdown package).

**Comment by williamstein** [comment]
@segevfiner, since this isn't part of the plans for prosemirror-markdown, and I had to worry about exactly these issues for cocalc (and I'm not too happy with the results; I just have experience), feel free to open a discussion with any questions or comments you have at https://github.com/sagemathinc/cocalc/discussions
